### ISSUE TITLE
I get a return -NULL after I plot the bfast image

### ISSUE THREAD

**Issue by 44jean** [bfast2/bfast#106]
hey i got stuck. I want to use the bfast package to detrend my carbon use efficiency time series , but the result of plotting always return 'NULL', is this correct? 
stl plot works and no red line and 'NULL'

this is my code in Rstudio
`Yt= ts(ee_chart$Cue,start=2000,frequency=12)
fit=stl(Yt,t.window=50,s.window='periodic',robust=T)
plot(fit)
fit <- bfast(Yt, h=0.15, season="dummy", max.iter = 10)
plot(fit)`

and this is the result
![image](https://user-images.githubusercontent.com/89766745/189817445-758293a4-2279-44fb-9d77-b40c1c60dc33.png)

![image](https://user-images.githubusercontent.com/89766745/189817526-d276524d-8958-440b-b6b0-d63f3224a610.png)

**Comment by GreatEmerald** [comment]
Yes, this is correct. The return of `NULL` is not really necessary and could be removed, but it doesn't really make a difference. Your output is correct, `Tt` shows the trend after breakpoint detection. In your case, no breakpoints were detected, therefore the trend is a straight line.

**Comment by 44jean** [comment]
thanks a lot!!!!!!
