### ISSUE TITLE
non-equal frequency in time series 

### ISSUE THREAD

**Issue by tanja98** [bfast2/bfast#107]
hello, 
how to handle an irregular/changing frequency using bfast ? as soon as I calculate the time series, the frequency is set to 1 automatically (without having explicitly set it). Therefore, I receive the error message "Time series frequency needs to be more than 1". do you have any solution on this ? 
I hope someone can help me, thx in advance

**Comment by GreatEmerald** [comment]
Yes, see `?bfastts`, specifically the irregular option. It creates a `ts` object that has a frequency equal to one year, which means one observation every day, with most observations set to missing values. That is fine as an input to most `bfast` functions.
