### ISSUE TITLE
How to extract slopes of lines through bfast? 

### ISSUE THREAD

**Issue by yiying99** [bfast2/bfast#108]
hey, my friends, is there anybody know how to extract slopes of lines through bfast?
This is my code: plot(fit,ANOVA=TRUE), there is data on picture, but I can't statistics.

**Comment by GreatEmerald** [comment]
You should be able to use the `coef()` function on the `breakpoints` object to get all of the coefficients, including the slope, of each of the segments.

**Comment by yiying99** [comment]
Thank you so much, it helps me a lot!
