### ISSUE TITLE
Stable period in the BFAST Lite algorith: Benefits and drawbacks

### ISSUE THREAD

**Issue by nikosGeography** [bfast2/bfast#112]
This is not a coding question but more of a theoretical one, so if it doesn't belong here feel free to close it.

I am about to use the [BFAST Lite](https://www.mdpi.com/2072-4292/13/16/3308) algorithm to perform a satellite time-series analysis (STSA). One of the parameters I have to specify is the lenght of the stable period (a time period within the time series data that is assumed to be free from significant structural changes).

The data I am about to use are monthly satellite nighttime lights (NTL) for the years 2013 to 2023. From a basic visual inspection, I saw that during 2014, there was a brightening in my study area and during the 2019 a dimming (due to COVID?). The issue is that I wanted to to use the years 2013 to 2018 as a stable period, but now I can't.

If I use them, the algorithm doesn't identify a break in 2019 (I haven't tested the behaviour of the method if I lessen the length of the stable period).

My question is: What are the benefits and drawbacks of a smaller stable period in the BFAST Lite method? Is there a recommended time length? I'm thinking to use data for the period 2018-2023.

Thank you.

**Comment by GreatEmerald** [comment]
I'm not sure if I understand what you mean exactly. The stable period definition is only relevant for BFAST Monitor, not BFAST Lite. In BFAST Lite, you specify the shortest segment size (`h` parameter), i.e. minimum time between breakpoints. The breakpoints themselves get detected automatically.

**Comment by nikosGeography** [comment]
I am sorry for not making the question more clear. First of all, the time I asked the question I thought that I had to specify a stable period in Lite just like in the "classical" BFAST. That's not the case, as you mentioned and as I learned by now.

**Comment by GreatEmerald** [comment]
To be exact, you only need to specify a stable period in BFAST Monitor. There is no difference between BFAST and BFAST Lite in that regard. It is also not needed for BFAST01.
