### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by GreatEmerald** [bfast2/bfast#24]
Travis CI can be used (at least as a starting point). It should be enabled for the repo by making a `travis.yml` file.

**Comment by arnikz** [comment]
see e.g. [testthat](https://github.com/r-lib/testthat) R package

**Comment by GreatEmerald** [comment]
Apparently Travis CI automatically picks those tests up, that's handy! It also should be able to run `R CMD check` by default as well, which in turn includes running the "examples" unit tests (but Codecov would probably not know about those).
Travis R documentation: https://docs.travis-ci.com/user/languages/r/

**Comment by arnikz** [comment]
My suggestion would be to follow [this](https://guide.esciencecenter.nl/best_practices/language_guides/r.html) guide with (R) best practices. Please have a look at one of our R projects [here](https://www.research-software.nl/software/ggir) (and the corresponding [repo](https://github.com/wadpac/GGIR)).

**Comment by GreatEmerald** [comment]
Solved by using GitHub Actions instead. Currently it's running a basic R CMD check, later on will make more extensive checks.
