### ISSUE TITLE
Add devel/master branches

### ISSUE THREAD

**Issue by GreatEmerald** [bfast2/bfast#25]
The master branch should be stable and aimed at CRAN submission, and other branches should be implementing new features (potentially breaking CRAN requirements).

**Comment by arnikz** [comment]
I've also added a [dev](https://github.com/bfast2/bfast/tree/dev) branch. Other branches implementing new features / bug fixes etc. should be created (e.g. using [user]_iss28) and merged after review into the `dev` branch. Let's keep the `master` branch for (pre-)release.

**Comment by mirt001** [comment]
In my opinion, we don't have enough developers to support a fast development (dev) and a slow development branch (master).
It is unclear to me what the advantages are to keep master only for pre-releases. I propose that we have a master branch that is used for development, with tagged versions that are release candidates or releases.

**Comment by GreatEmerald** [comment]
Indeed, keeping the master for preparation for (pre-)release is a bit pointless, considering that everything that we're doing is in fact preparation for (pre-)release. There is already a read-only mirror of CRAN on GitHub, we don't need to make another one. And it's useful for people to tell at a glance that this repo is in fact not dead.
