### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by arnikz** [bfast2/bfast#32]
- [x] update `README.md` file
- [x] add `CONTRIBUTING.md` file

**Comment by GreatEmerald** [comment]
I think this is a small enough change that it can go to the master branch as well. How should we handle that? As a PR to the master branch also from the issue branch, or from dev?

**Comment by arnikz** [comment]
Let's keep this change in the `dev` branch for time being. We will then merge all changes in this branch with `master` via PR, as soon as we are ready with the new version(s) `1.5.8` and/or `1.6.0`. My suggestion would be to define a list of TODOs (milestone) including bug fixes and/or new features, followed by an agreement.

**Comment by GreatEmerald** [comment]
It's now merged as per issue #25.
