### ISSUE TITLE
bfast0n/Error in UseMethod("breakpoints")

### ISSUE THREAD

**Issue by Eco-bin** [bfast2/bfast#69]
When run the bfast0n.r (https://github.com/bfast2/bfast/tree/master/examples), an error occurred. "Error in UseMethod("breakpoints"): no applicable method for 'breakpoints' applied to an object of class 'data.frame' "
ps:I install both packages with:library(devtools)  install_github("bfast2/strucchange")  install_github("bfast2/bfast")

**Comment by GreatEmerald** [comment]
It works for me, but I just updated the function, so perhaps just try rerunning `install_github("bfast2/bfast")` and running the code again.

**Comment by Eco-bin** [comment]
It's ok now, thanks a lot!
