### ISSUE TITLE
Update .Rbuildignore 

### ISSUE THREAD

**Issue by appelmar** [bfast2/bfast#72]
Add `^\.github$` to .Rbuildignore

**Comment by appelmar** [comment]
R CMD check --as-cran also complains about the `examples` directory. I guess this is used only for roxygen and can be safely added to `.Rbuildignore`, is that correct @GreatEmerald?

**Comment by GreatEmerald** [comment]
Yes, indeed, this is used for getting the examples into the documentation in an easy to edit fashion.
