### ISSUE TITLE
R-hub check on Solaris

### ISSUE THREAD

**Issue by appelmar** [bfast2/bfast#88]
Before submission to CRAN, we should do a R CMD check on a Solaris platform to make sure that the C++ code does not produce warnings / notes as with `strucchangeRcpp`.

**Comment by GreatEmerald** [comment]
I ran it and it gave a success.

**Comment by GreatEmerald** [comment]
Output was: https://builder.r-hub.io/status/bfast_1.6.0.tar.gz-9517312466b2c0a21ae24d24e280f77e (I already fixed the issue there in #90)

**Comment by GreatEmerald** [comment]
I also ran rchk, and I don't see any issues, but I'm not sure if it did anything: https://builder.r-hub.io/status/bfast_1.6.0.tar.gz-b4a7b9d61e744805bd182fd19135740c
